In [1]:
import numpy as np

# Creating NumPy array

We will use pandas here to read the csv file for the sake of simplicity. Import pandas library and use the read_csv() to get the csv file in the form of a DataFrame. 

In [2]:
import pandas as pd
data = pd.read_csv('starbucks-menu-nutrition-drinks.csv')
print(data)

                                                 Name  Calories  Fat (g)  \
0            Cool Lime Starbucks Refreshers™ Beverage        45      0.0   
1      Strawberry Acai Starbucks Refreshers™ Beverage        80      0.0   
2   Very Berry Hibiscus Starbucks Refreshers™ Beve...        60      0.0   
3             Evolution Fresh™ Organic Ginger Limeade       110      0.0   
4                                         Iced Coffee         0      0.0   
..                                                ...       ...      ...   
79                                    Latte Macchiato       190      7.0   
80                                    Latte Macchiato       190      7.0   
81                                      Vanilla Latte       250      6.0   
82                              White Chocolate Mocha       360     11.0   
83         Cinnamon Dolce Frappuccino® Blended Coffee       350      4.5   

    Carb. (g)  Fiber (g)  Protein  Sodium  
0          11          0        0      10  

Let us create a numpy array using np.array() function. Here we will create a simple numerical numpy array of calories function from our previously extracted data.

In [3]:
cal = np.array(data['Calories'])
cal

array([ 45,  80,  60, 110,   0, 130, 140, 130,  80,  60, 150, 140, 140,
       150,  70, 120, 140,  60, 120, 140, 150, 140,  30,  70,  30,  70,
        30,  90,  60, 130, 140, 130,  90,  90, 210, 200,  60,  50,  10,
        60, 150, 140, 140, 150,  70, 120, 140,  60, 120, 140, 150, 140,
         5,  10,   5,   5,   5,   5,   0,   5,  70,   5, 110, 320, 430,
       190, 290, 120, 250, 260, 250, 180, 130, 230, 250, 200, 260, 190,
       300, 190, 190, 250, 360, 350])

Thus, we can see all the calorie contents in each of our drinks present in data. 

You can also create an array from scratch from list as follows:

In [4]:
li = [11,2,53,74,5]
nd_li = np.array(li)
nd_li

array([11,  2, 53, 74,  5])

A numpy array can also contain strings, lists, numbers, etc, but all the data in the array should be of same type.

In [5]:
str_li = ['Wiley', 'Python']
nd_str_li = np.array(str_li)
nd_str_li

array(['Wiley', 'Python'], dtype='<U6')

A array or a matrix can be created as follows.

In [45]:
mat1 = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])        # This is a 3x3 matrix


We can also create an ndarray containing all zeros or all ones of any size instead of writing a whole big array manually.

In [7]:
z = np.zeros(100, dtype=int)
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
z = np.zeros([5,5], dtype=float)
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
o = np.ones(50, dtype=int)
o

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [10]:
o = np.ones([5,5], dtype=str)
o

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

The arange function takes the arguments start, stop and step and returns an array with evenly spaced elements as per the interval. The interval mentioned is half-opened i.e.[start,stop)

In [11]:
arr1 = np.arange(3)
arr1

array([0, 1, 2])

In [12]:
arr2 = np.arange(1,10,1)
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr3 = np.arange(2,30,2)
arr3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

# NumPy Array Manipulation 

copy() is a function which is used to copy contents of one array to another. Suppose we extract a column say 'Protein' from our data and convert it to numpy and make a copy of it. 

In [14]:
protein = np.array(data['Protein'])
print(protein)

protein_copy = np.copy(protein)
print(protein_copy)

[ 0  0  0  0  0  5  5  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  5  5  5  0  0 20 20  1  1  1  0  0  0  0  0  0  0  0  0
  0  0  0  0  1  1  1  1  0  0  0  0  1  1  1 14 12 13 13  8 10 11 12 12
  8  9 10  7 11  7 10 12 12 12 14 15]
[ 0  0  0  0  0  5  5  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  5  5  5  0  0 20 20  1  1  1  0  0  0  0  0  0  0  0  0
  0  0  0  0  1  1  1  1  0  0  0  0  1  1  1 14 12 13 13  8 10 11 12 12
  8  9 10  7 11  7 10 12 12 12 14 15]


As we can see that protein_copy copied all the contents of the protein array and thus both the arrays are same. 

We can also append certain values to the numpy array using the append() function. This function will insert an element at the end of the list. 

In [15]:
arr1 = [3,4,5,2]
arr1.append(10)
arr1

[3, 4, 5, 2, 10]

append() function can also be used to append an array to another array. 

In [16]:
arr2 = [4.3, 23.33, 90.8, 32.75]
arr1.append(arr2)
arr1

[3, 4, 5, 2, 10, [4.3, 23.33, 90.8, 32.75]]

The concatenate function in NumPy joins two or more arrays along a specified axis. 

In [17]:
fruits = np.array(['apple', 'banana', 'orange', 'kiwi'])
veggies = np.array(['kale', 'cabbage', 'avocado'])
print(np.concatenate((fruits, veggies)))

arr1 = np.array([1,23])
arr2 = np.array([3,4])
arr3 = np.concatenate((arr1,arr2))
print(arr3)

['apple' 'banana' 'orange' 'kiwi' 'kale' 'cabbage' 'avocado']
[ 1 23  3  4]


Numpy provides some helper functions for stacking elements in two arrays in different ways. 
hstack() is a function that stacks elements in a row. 

In [18]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr) 

[1 2 3 4 5 6]


vstack() stacks a column wise

In [19]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr) 

[[1 2 3]
 [4 5 6]]


dstack() stacks along height, which is the same as depth.

In [20]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr) 

[[[1 4]
  [2 5]
  [3 6]]]


Let's observe matrix operations using numpy

In [21]:
matrix1 = np.array([[1,2],
                    [8,7]])
matrix2 = np.array([[5,6],
                    [0,9]])

# adding two matrix
print("Addition of two matrix")
print(np.add(matrix1, matrix2))

Addition of two matrix
[[ 6  8]
 [ 8 16]]


In [22]:
# subtraction two matrix
print("Subtraction of two matrix")
print(np.subtract(matrix1, matrix2))

Subtraction of two matrix
[[-4 -4]
 [ 8 -2]]


In [23]:
# Multiplication of two matrix
print("Multiplication of two matrix")
print(np.dot(matrix1, matrix2))

Multiplication of two matrix
[[  5  24]
 [ 40 111]]


It is noticeable here that the multiply() function will simply multiply the numbers at same indexes in two matrices instead of doing the dot product. 

In [24]:
#Multiplication of two simple arrays
print("Multiplication of array")
print(np.multiply(matrix1, matrix2))

Multiplication of array
[[ 5 12]
 [ 0 63]]


# Reshaping NumPy array 

The numpy.reshape() function shapes an array without changing the data of the array. Here we are changing a 1D array to 2x4 dimension. 

In [25]:
arr1 = np.arange(8)
arr1_re = arr1.reshape(2, 4)
arr1_re

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

We can also convert to a 3D matrix as follows: 

In [26]:
arr2 = np.arange(8).reshape(2, 2, 2)
arr2

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# Operations on NumPy 

char.lower() function is used to convert all the characters in the array in lowercase. 

In [27]:
import numpy as np

fruits = np.array(['Kiwi', 'ORANGES', 'StrawBerries'])
fruits = np.char.lower(fruits)
print(fruits)

['kiwi' 'oranges' 'strawberries']


char.upper() function is used to convert all the characters in the array in uppercase. 

In [28]:
fruits = np.array(['Kiwi', 'ORANGES', 'StrawBerries'])
fruits = np.char.upper(fruits)
print(fruits)

['KIWI' 'ORANGES' 'STRAWBERRIES']


numpy.split() function returns a list of strings after breaking the given string by the specified separator.

In [29]:
str1 = "Hello World!"
np1 = np.char.split(str1)
print(np1)

['Hello', 'World!']


numpy.join() function is a string method and returns a string in which the elements of sequence have been joined by str separator.

In [30]:
print(np.char.join('-', 'wiley'))

print(np.char.join(['-', ':', '.'], ['python', 'for', 'beginners']))

w-i-l-e-y
['p-y-t-h-o-n' 'f:o:r' 'b.e.g.i.n.n.e.r.s']


numpy.bitwise_and() function is used to compute the bit-wise AND of two array element-wise. This function computes the bit-wise AND of the underlying binary representation of the integers in the input arrays.

In [31]:
arr1 = [2, 8, 125]
arr2 = [3, 3, 115]
  
print ("Input array1 : ", arr1) 
print ("Input array2 : ", arr2)
   
out_arr = np.bitwise_and(arr1, arr2) 
print ("Output array after bitwise_and: ", out_arr) 

Input array1 :  [2, 8, 125]
Input array2 :  [3, 3, 115]
Output array after bitwise_and:  [  2   0 113]


numpy.bitwise_or() function is used to compute the bit-wise OR of two array element-wise. This function computes the bit-wise OR of the underlying binary representation of the integers in the input arrays.

In [32]:
arr1 = [2, 8, 125]
arr2 = [3, 3, 115]
  
print ("Input array1 : ", arr1) 
print ("Input array2 : ", arr2)
   
out_arr = np.bitwise_or(arr1, arr2) 
print ("Output array after bitwise_or: ", out_arr) 

Input array1 :  [2, 8, 125]
Input array2 :  [3, 3, 115]
Output array after bitwise_or:  [  3  11 127]


numpy.bitwise_xor() function is used to compute the bit-wise XOR of two array element-wise. This function computes the bit-wise XOR of the underlying binary representation of the integers in the input arrays.

In [33]:
arr1 = [2, 8, 125]
arr2 = [3, 3, 115]
  
print ("Input array1 : ", arr1) 
print ("Input array2 : ", arr2)
   
out_arr = np.bitwise_xor(arr1, arr2) 
print ("Output array after bitwise_xor: ", out_arr) 

Input array1 :  [2, 8, 125]
Input array2 :  [3, 3, 115]
Output array after bitwise_xor:  [ 1 11 14]


numpy.invert() function is used to compute the bit-wise Inversion of an array element-wise. It computes the bit-wise NOT of the underlying binary representation of the integers in the input arrays.

In [34]:
arr1 = [2, 8, 125]
print ("Input array1 : ", arr1) 
out_arr = np.invert(arr1) 
print ("Output array after invert: ", out_arr) 

Input array1 :  [2, 8, 125]
Output array after invert:  [  -3   -9 -126]


# Slicing in NumPy array 

Slicing is of the form a[x:y] means that output all the elements from xth to y-1th index.

In [35]:
 # Arange elements from 0 to 19
a = np.arange(20)
print("Array is:",a)
 
# a[start:stop]
print("\na[3:7] = ", a[3:7])
 
# The : operator means all elements till the end.
print("\na[10:] = ",a[10:])

# Negative integer means start from the end. so -1th index will actually be the last element in array
print("\na[-3:-7] = ", a[-7:-3])

Array is: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

a[3:7] =  [3 4 5 6]

a[10:] =  [10 11 12 13 14 15 16 17 18 19]

a[-3:-7] =  [13 14 15 16]


# Sorting and Searching 

Using dstack we combine two columns 'Proteins' and 'Name' so that we know the contents of each beverage.

In [36]:
a = np.array(data['Protein'], dtype=int)
b = np.array(data['Name'])
np1 = np.dstack((a,b))


In [37]:
np.shape(np1)

(1, 84, 2)

As we see that we our array has become 3 dimensional so we reshape it using reshape() for sorting.

In [38]:
np1 = np1.reshape(84,2)

In [39]:
np1

array([[0, 'Cool Lime Starbucks Refreshers™ Beverage'],
       [0, 'Strawberry Acai Starbucks Refreshers™ Beverage'],
       [0, 'Very Berry Hibiscus Starbucks Refreshers™ Beverage'],
       [0, 'Evolution Fresh™ Organic Ginger Limeade'],
       [0, 'Iced Coffee'],
       [5, 'Iced Espresso Classics - Vanilla Latte'],
       [5, 'Iced Espresso Classics - Caffe Mocha'],
       [5, 'Iced Espresso Classics - Caramel Macchiato'],
       [0, 'Shaken Sweet Tea'],
       [0, 'Tazo® Bottled Berry Blossom White'],
       [0, 'Tazo® Bottled Black Mango'],
       [0, 'Tazo® Bottled Black with Lemon'],
       [0, 'Tazo® Bottled Brambleberry'],
       [0, 'Tazo® Bottled Giant Peach'],
       [0, 'Tazo® Bottled Iced Passion'],
       [0, 'Tazo® Bottled Lemon Ginger'],
       [0, 'Tazo® Bottled Organic Black Lemonade'],
       [0, 'Tazo® Bottled Organic Iced Black Tea'],
       [0, 'Tazo® Bottled Organic Iced Green Tea'],
       [0, 'Tazo® Bottled Plum Pomegranate'],
       [0, 'Tazo® Bottled Tazober

To sort the fats column, we use sort() function.

In [40]:
np1 = np.array(data['Fat (g)'], dtype=int) 
np.sort(np1)

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  2,  2,  2,  2,  2,  2,  2,  2,  4,  4,  4,  4,  4,  5,  6,
        6,  6,  6,  7,  7,  7,  7,  7,  7,  8,  8,  9,  9,  9, 11, 26])

As we can see that the maximum amount of fat content is 26 units. So we try to find the beverage with maiximum amount of fat content using searching. Searching is done with the help of where() function.

First we will dstack the array so that we associate the fat content with their respective drink.

In [41]:
np1 = np.array(data['Fat (g)'], dtype=int) 
np2 = np.array(data['Name'])

np3 = np.dstack((np1, np2))

Now we search the row which has fat=26 grams

In [42]:
i = np.where(np3 == 26)

In [43]:
i

(array([0]), array([64]), array([0]))

Thus, we get the  location at (0,64)

In [44]:
np3[0,64]

array([26, 'Starbucks® Signature Hot Chocolate'], dtype=object)

Thus, the Starbucks' Signature Hot Chocolate contains the highest fat content. So now you can perform similar operations to check various contents in other drinks.